"""Audit log endpoints — immutable decision trail."""
from __future__ import annotations

from datetime import datetime, timezone
from fastapi import APIRouter, Query

router = APIRouter()

_DEMO_AUDIT = [
    {"id": "a001", "event_type": "CYCLE_STARTED", "actor": "coordinator",
     "symbol": None, "severity": "INFO", "summary": "Analysis cycle started, 17 symbols",
     "created_at": "2024-12-04T10:00:00Z"},
    {"id": "a002", "event_type": "AGENT_SIGNAL", "actor": "MarketDataAgent",
     "symbol": "AAPL", "severity": "INFO",
     "summary": "BUY signal — RSI oversold 28.4, MACD bullish cross, uptrend", "confidence": 72.5,
     "created_at": "2024-12-04T10:00:03Z"},
    {"id": "a003", "event_type": "RISK_APPROVED", "actor": "RiskAgent",
     "symbol": "AAPL", "severity": "INFO", "summary": "Trade APPROVED — all risk checks passed",
     "created_at": "2024-12-04T10:00:04Z"},
    {"id": "a004", "event_type": "ORDER_SUBMITTED", "actor": "ExecutionAgent",
     "symbol": "AAPL", "severity": "INFO",
     "summary": "BUY 25 AAPL @ $183.40 paper order submitted", "created_at": "2024-12-04T10:00:04Z"},
    {"id": "a005", "event_type": "ORDER_FILLED", "actor": "PaperBroker",
     "symbol": "AAPL", "severity": "INFO",
     "summary": "BUY 25 AAPL filled @ $183.49 (slippage $0.09, commission $4.59)",
     "created_at": "2024-12-04T10:00:05Z"},
    {"id": "a006", "event_type": "RISK_REJECTED", "actor": "RiskAgent",
     "symbol": "TSLA", "severity": "WARN",
     "summary": "Trade REJECTED — elevated volatility ATR=4.2% exceeds threshold",
     "created_at": "2024-12-04T10:00:06Z"},
    {"id": "a007", "event_type": "CYCLE_COMPLETE", "actor": "coordinator",
     "symbol": None, "severity": "INFO",
     "summary": "Cycle complete: 3 BUY, 1 SELL, 13 HOLD, 2 REJECTED, 2 BLOCKED",
     "created_at": "2024-12-04T10:00:10Z"},
]


@router.get("/logs")
async def get_audit_logs(
    limit: int = Query(50, ge=1, le=500),
    symbol: str = Query(None),
    event_type: str = Query(None),
    severity: str = Query(None),
):
    logs = _DEMO_AUDIT
    if symbol:
        logs = [l for l in logs if l.get("symbol") == symbol.upper()]
    if event_type:
        logs = [l for l in logs if l.get("event_type") == event_type.upper()]
    if severity:
        logs = [l for l in logs if l.get("severity") == severity.upper()]
    return {"logs": logs[-limit:][::-1], "count": len(logs)}


@router.get("/decision/{decision_id}/explain")
async def explain_decision(decision_id: str):
    return {
        "decision_id": decision_id,
        "explanation": (
            "Decision was generated by running all 13 agents sequentially. "
            "MarketDataAgent found RSI=28.4 (oversold) and a MACD bullish cross. "
            "NewsAgent found 2 positive articles. BullAgent projected +8.5% upside. "
            "BearAgent identified volatility risk (ATR=1.8%). RiskAgent APPROVED with "
            "default 2% sizing. PortfolioManager applied Kelly criterion (f=0.043) and "
            "account type (balanced) to size at 2.0%."
        ),
    }
