"""Signals feed page."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Signals | OmniAlpha", page_icon="📡", layout="wide")
st.title("📡 Signal Feed")

st.info("Signals are generated by the multi-agent pipeline. Only APPROVED signals are proposed for execution.")

# Filters
col1, col2, col3 = st.columns(3)
asset_filter = col1.multiselect("Asset Class", ["STOCK", "ETF", "CRYPTO", "FOREX"],
                                 default=["STOCK", "ETF", "CRYPTO", "FOREX"])
action_filter = col2.multiselect("Action", ["BUY", "SELL", "HOLD"], default=["BUY", "SELL"])
min_conf = col3.slider("Min Confidence", 0, 100, 50)

@st.cache_data(ttl=60)
def load_signals():
    try:
        from services.agents.coordinator import get_coordinator
        from libs.common.config import settings
        coord = get_coordinator()
        decisions = coord.run_cycle()
        rows = []
        for d in decisions:
            rows.append({
                "Symbol": d.symbol,
                "Asset": d.asset_class.upper(),
                "Action": d.action,
                "Confidence": round(d.confidence, 1),
                "Risk Score": round(d.risk_score, 1),
                "Risk Verdict": d.risk_verdict,
                "Entry Price": round(d.entry_price, 4),
                "Stop Loss": round(d.stop_loss, 4) if d.stop_loss else None,
                "Take Profit": round(d.take_profit, 4) if d.take_profit else None,
                "Size %": round(d.position_size_pct * 100, 2),
                "Holding": d.expected_holding_period,
            })
        return pd.DataFrame(rows)
    except Exception:
        return pd.DataFrame([
            {"Symbol": "AAPL", "Asset": "STOCK", "Action": "BUY", "Confidence": 72.5,
             "Risk Score": 28.0, "Risk Verdict": "APPROVED", "Entry Price": 185.20,
             "Stop Loss": 180.64, "Take Profit": 196.72, "Size %": 2.00, "Holding": "2-5 days"},
            {"Symbol": "MSFT", "Asset": "STOCK", "Action": "BUY", "Confidence": 68.3,
             "Risk Score": 22.0, "Risk Verdict": "APPROVED", "Entry Price": 422.10,
             "Stop Loss": 411.20, "Take Profit": 447.42, "Size %": 2.00, "Holding": "2-5 days"},
            {"Symbol": "BTC/USDT", "Asset": "CRYPTO", "Action": "BUY", "Confidence": 61.0,
             "Risk Score": 45.0, "Risk Verdict": "APPROVED", "Entry Price": 68200.0,
             "Stop Loss": 64190.0, "Take Profit": 72374.0, "Size %": 2.00, "Holding": "2-5 days"},
            {"Symbol": "TSLA", "Asset": "STOCK", "Action": "HOLD", "Confidence": 44.0,
             "Risk Score": 72.0, "Risk Verdict": "REJECTED", "Entry Price": 251.0,
             "Stop Loss": None, "Take Profit": None, "Size %": 0.00, "Holding": "N/A"},
            {"Symbol": "EURUSD=X", "Asset": "FOREX", "Action": "HOLD", "Confidence": 48.0,
             "Risk Score": 30.0, "Risk Verdict": "APPROVED", "Entry Price": 1.0853,
             "Stop Loss": None, "Take Profit": None, "Size %": 0.00, "Holding": "N/A"},
        ])


df = load_signals()
if not df.empty:
    mask = (
        df["Asset"].isin(asset_filter) &
        df["Action"].isin(action_filter) &
        (df["Confidence"] >= min_conf)
    )
    df_filtered = df[mask]

    st.markdown(f"**{len(df_filtered)} signals** matching filters")

    def highlight_action(row):
        if row["Action"] == "BUY":
            return ["background-color: #004400"] * len(row)
        elif row["Action"] == "SELL":
            return ["background-color: #440000"] * len(row)
        return [""] * len(row)

    st.dataframe(
        df_filtered.style.apply(highlight_action, axis=1),
        use_container_width=True,
        hide_index=True,
    )
